[package]
name = "cogrrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpu = {path = "crates/gpu"}
window = {path = "crates/window"}

[dev-dependencies]
bytemuck = {version = "1.7", default-features = false, features = [ "derive" ]}
rayon = {version="1.6"}
anyhow = "1.0"