[package]
name = "window"
version = "0.1.0"
authors = ["jasperdewinther <31817802+jasperdewinther@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28"
anyhow = "1.0"